# Generated by Django 5.2.8 on 2025-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deploy_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('mobile', models.IntegerField(unique=True)),
            ],
        ),
    ]
